In [1]:
import pandas as pd

### Large Listings Dataset

In [2]:
# Large Airbnb listings dataset url
listings_url = "https://data.insideairbnb.com/canada/on/toronto/2025-11-11/data/listings.csv.gz"

# 1. Read just the first 5 rows to 'peek'
# Pandas handles the .gz compression automatically!
listings_df = pd.read_csv(listings_url, nrows=5)

# 2. Look at the column names (there are over 70!)
print(f"Total Columns: {len(listings_df.columns)}")
print(listings_df.columns)

# 3. View the data
listings_df.head()

Total Columns: 79
Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='str')

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1419,https://www.airbnb.com/rooms/1419,20251111064035,2025-11-11,previous scrape,Beautiful home in amazing area!,"This large, family home is located in one of T...",The apartment is located in the Ossington stri...,https://a0.muscache.com/pictures/76206750/d643...,1565,...,5.00,5.00,5.00,NaN,f,1,1,0,0,0.05
1,8077,https://www.airbnb.com/rooms/8077,20251111064035,2025-11-11,previous scrape,Downtown Harbourfront Private Room,Guest room in a luxury condo with access to al...,NaN,https://a0.muscache.com/pictures/11780344/141c...,22795,...,4.90,4.92,4.83,NaN,f,2,1,1,0,0.85
2,26654,https://www.airbnb.com/rooms/26654,20251111064035,2025-11-11,city scrape,"World Class @ CN Tower, convention centre, The...","CN Tower, TIFF Bell Lightbox, Metro Convention...",There's a reason they call it the Entertainmen...,https://a0.muscache.com/pictures/81811785/5dcd...,113345,...,4.78,4.87,4.69,NaN,f,3,3,0,0,0.25
3,27423,https://www.airbnb.com/rooms/27423,20251111064035,2025-11-12,city scrape,Executive Studio Unit- Ideal for One Person,"Brand new, fully furnished studio basement apa...",NaN,https://a0.muscache.com/pictures/176936/b687ed...,118124,...,5.00,4.88,4.88,NaN,f,1,1,0,0,0.16
4,30931,https://www.airbnb.com/rooms/30931,20251111064035,2025-11-11,previous scrape,Downtown Toronto - Waterview Condo,Split level waterfront condo with a breathtaki...,NaN,https://a0.muscache.com/pictures/227971/e8ebd7...,22795,...,NaN,NaN,NaN,NaN,f,2,1,1,0,0.01

In [3]:
listings_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            5 non-null      int64
 1   listing_url                                   5 non-null      str
 2   scrape_id                                     5 non-null      int64
 3   last_scraped                                  5 non-null      str
 4   source                                        5 non-null      str
 5   name                                          5 non-null      str
 6   description                                   5 non-null      str
 7   neighborhood_overview                         2 non-null      str
 8   picture_url                                   5 non-null      str
 9   host_id                                       5 non-null      int64
 10  host_url                                      5 non-null      str
 11  host_name                                     5 non-null      str
 12  host_since                                    5 non-null      str
 13  host_location                                 4 non-null      str
 14  host_about                                    5 non-null      str
 15  host_response_time                            1 non-null      str
 16  host_response_rate                            1 non-null      str
 17  host_acceptance_rate                          1 non-null      str
 18  host_is_superhost                             5 non-null      str
 19  host_thumbnail_url                            5 non-null      str
 20  host_picture_url                              5 non-null      str
 21  host_neighbourhood                            5 non-null      str
 22  host_listings_count                           5 non-null      int64
 23  host_total_listings_count                     5 non-null      int64
 24  host_verifications                            5 non-null      str
 25  host_has_profile_pic                          5 non-null      str
 26  host_identity_verified                        5 non-null      str
 27  neighbourhood                                 2 non-null      str
 28  neighbourhood_cleansed                        5 non-null      str
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      5 non-null      float64
 31  longitude                                     5 non-null      float64
 32  property_type                                 5 non-null      str
 33  room_type                                     5 non-null      str
 34  accommodates                                  5 non-null      int64
 35  bathrooms                                     2 non-null      float64
 36  bathrooms_text                                5 non-null      str
 37  bedrooms                                      4 non-null      float64
 38  beds                                          2 non-null      float64
 39  amenities                                     5 non-null      str
 40  price                                         2 non-null      str
 41  minimum_nights                                5 non-null      int64
 42  maximum_nights                                5 non-null      int64
 43  minimum_minimum_nights                        5 non-null      int64
 44  maximum_minimum_nights                        5 non-null      int64
 45  minimum_maximum_nights                        5 non-null      int64
 46  maximum_maximum_nights                        5 non-null      int64
 47  minimum_nights_avg_ntm                        5 non-null      float64
 48  maximum_nights_avg_ntm                        5 non-null      float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              3 non-null      str
 51  availability_30                               5 non-null      int64
 52  availability_60                               5 non-null      int64
 53  availability_90                               5 non-null      int64
 54  availability_365                              5 non-null      int64
 55  calendar_last_scraped                         5 non-null      str
 56  number_of_reviews                             5 non-null      int64
 57  number_of_reviews_ltm                         5 non-null      int64
 58  number_of_reviews_l30d                        5 non-null      int64
 59  availability_eoy                              5 non-null      int64
 60  number_of_reviews_ly                          5 non-null      int64
 61  estimated_occupancy_l365d                     5 non-null      int64
 62  estimated_revenue_l365d                       2 non-null      float64
 63  first_review                                  5 non-null      str
 64  last_review                                   5 non-null      str
 65  review_scores_rating                          5 non-null      float64
 66  review_scores_accuracy                        4 non-null      float64
 67  review_scores_cleanliness                     4 non-null      float64
 68  review_scores_checkin                         4 non-null      float64
 69  review_scores_communication                   4 non-null      float64
 70  review_scores_location                        4 non-null      float64
 71  review_scores_value                           4 non-null      float64
 72  license                                       0 non-null      float64
 73  instant_bookable                              5 non-null      str
 74  calculated_host_listings_count                5 non-null      int64
 75  calculated_host_listings_count_entire_homes   5 non-null      int64
 76  calculated_host_listings_count_private_rooms  5 non-null      int64
 77  calculated_host_listings_count_shared_rooms   5 non-null      int64
 78  reviews_per_month                             5 non-null      float64
dtypes: float64(19), int64(26), str(34)
memory usage: 3.2 KB

### Small Listings Dataset

In [4]:
# The URL for Toronto Listings (compressed)
url = "https://data.insideairbnb.com/canada/on/toronto/2025-11-11/visualisations/listings.csv"

# 1. Read just the first 5 rows to 'peek'
# Pandas handles the .gz compression automatically!
df_peek = pd.read_csv(url, nrows=5)

# 2. Look at the column names (there are over 70!)
print(f"Total Columns: {len(df_peek.columns)}")
print(df_peek.columns)

df_peek.head()

Total Columns: 18
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='str')

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,1419,Beautiful home in amazing area!,1565,Alexandra,NaN,Little Portugal,43.64590,-79.42423,Entire home/apt,NaN,28,6,2017-08-07,0.05,1,0,0,NaN
1,8077,Downtown Harbourfront Private Room,22795,Kathie & Larry,NaN,Waterfront Communities-The Island,43.64080,-79.37673,Private room,NaN,180,167,2013-08-27,0.85,2,0,0,NaN
2,26654,"World Class @ CN Tower, convention centre, The...",113345,Adela,NaN,Waterfront Communities-The Island,43.64608,-79.39032,Entire home/apt,133.0,28,45,2025-02-01,0.25,3,140,2,NaN
3,27423,Executive Studio Unit- Ideal for One Person,118124,Brent,NaN,South Riverdale,43.66884,-79.32725,Entire home/apt,75.0,365,31,2025-01-01,0.16,1,11,1,NaN
4,30931,Downtown Toronto - Waterview Condo,22795,Kathie & Larry,NaN,Waterfront Communities-The Island,43.64015,-79.37625,Entire home/apt,NaN,180,1,2010-08-11,0.01,2,0,0,NaN

### Large Reviews Dataset

In [5]:
# Large Airbnb reviews dataset url
reviews_url = "https://data.insideairbnb.com/canada/on/toronto/2025-11-11/data/reviews.csv.gz"

# 1. Read just the first 5 rows to 'peek'
# Pandas handles the .gz compression automatically!
reviews_df = pd.read_csv(reviews_url, nrows=5)

# 2. Look at the column names (there are over 70!)
print(f"Total Columns: {len(reviews_df.columns)}")
print(reviews_df.columns)

reviews_df.head()

Total Columns: 6
Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='str')

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,9974111,105972997,2016-10-03,74630712,Lily,I absolutely loved the location!! I was there ...
1,9974111,125205050,2017-01-04,23609,Mark,"Stayed here for 2 weeks , great location , gre..."
2,9974111,191232367,2017-09-06,147270253,Dianne,Awesome location! Communication with Shoug was...
3,9974111,196001139,2017-09-21,5590969,Charie,Had a really great two week stay at Shoug's pl...
4,9974111,197975881,2017-09-27,76030814,Oswald,great and easy stay - no issues at all

In [6]:
reviews_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   listing_id     5 non-null      int64
 1   id             5 non-null      int64
 2   date           5 non-null      str
 3   reviewer_id    5 non-null      int64
 4   reviewer_name  5 non-null      str
 5   comments       5 non-null      str
dtypes: int64(3), str(3)
memory usage: 372.0 bytes

### Small Reviews Dataset

In [7]:
# The URL for Toronto Listings (compressed)
url = "https://data.insideairbnb.com/canada/on/toronto/2025-11-11/visualisations/reviews.csv"

# 1. Read just the first 5 rows to 'peek'
# Pandas handles the .gz compression automatically!
df_peek = pd.read_csv(url, nrows=5)

# 2. Look at the column names (there are over 70!)
print(f"Total Columns: {len(df_peek.columns)}")
print(df_peek.columns)

df_peek.head()

Total Columns: 2
Index(['listing_id', 'date'], dtype='str')

   listing_id        date
0     9974111  2016-10-03
1     9974111  2017-01-04
2     9974111  2017-09-06
3     9974111  2017-09-21
4     9974111  2017-09-27

### Calendar Dataset

In [8]:
# The URL for Toronto Listings (compressed)
url = "https://data.insideairbnb.com/canada/on/toronto/2025-11-11/data/calendar.csv.gz"

# 1. Read just the first 5 rows to 'peek'
# Pandas handles the .gz compression automatically!
df_peek = pd.read_csv(url, nrows=10)

# 2. Look at the column names (there are over 70!)
print(f"Total Columns: {len(df_peek.columns)}")
print(df_peek.columns)

df_peek.head(10)

Total Columns: 7
Index(['listing_id', 'date', 'available', 'price', 'adjusted_price',
       'minimum_nights', 'maximum_nights'],
      dtype='str')

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,9974111,2025-11-11,f,NaN,NaN,28,1125
1,9974111,2025-11-12,f,NaN,NaN,28,1125
2,9974111,2025-11-13,f,NaN,NaN,28,1125
3,9974111,2025-11-14,f,NaN,NaN,28,1125
4,9974111,2025-11-15,f,NaN,NaN,28,1125
5,9974111,2025-11-16,f,NaN,NaN,28,1125
6,9974111,2025-11-17,f,NaN,NaN,28,1125
7,9974111,2025-11-18,f,NaN,NaN,28,1125
8,9974111,2025-11-19,f,NaN,NaN,28,1125
9,9974111,2025-11-20,f,NaN,NaN,28,1125

### Neighbourhoods dataset

In [9]:
# The URL for Toronto Listings (compressed)
url = "https://data.insideairbnb.com/canada/on/toronto/2025-11-11/visualisations/neighbourhoods.csv"

# 1. Read just the first 5 rows to 'peek'
# Pandas handles the .gz compression automatically!
df_peek = pd.read_csv(url, nrows=10)

# 2. Look at the column names (there are over 70!)
print(f"Total Columns: {len(df_peek.columns)}")
print(df_peek.columns)

df_peek.head(10)

Total Columns: 2
Index(['neighbourhood_group', 'neighbourhood'], dtype='str')

   neighbourhood_group                 neighbourhood
0                  NaN               Agincourt North
1                  NaN  Agincourt South-Malvern West
2                  NaN                     Alderwood
3                  NaN                         Annex
4                  NaN             Banbury-Don Mills
5                  NaN                Bathurst Manor
6                  NaN           Bay Street Corridor
7                  NaN               Bayview Village
8                  NaN         Bayview Woods-Steeles
9                  NaN          Bedford Park-Nortown

### City of Toronto Short Term Rentals Dataset

In [10]:
# Registered short-term rentals dataset url
st_rental_url = 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/2ab20f80-3599-486a-8f8a-9cb59117977c/resource/9c235257-b09f-441e-bcad-1495607f9a82/download/short-term-rental-registrations-data.csv'

# 1. Read just the first 10 rows to 'peek'
# Use pd.read_excel for .xlsx files
st_rental_df = pd.read_csv(st_rental_url, nrows=10)

# 2. Look at the column names
print(f"Total Columns: {len(st_rental_df.columns)}")
print(st_rental_df.columns)

st_rental_df.head(10)

Total Columns: 8
Index(['_id', 'operator_registration_number', 'address', 'unit', 'postal_code',
       'property_type', 'ward_number', 'ward_name'],
      dtype='str')

,_id,operator_registration_number,address,unit,postal_code,property_type,ward_number,ward_name
0,6901344,STR-2209-JCLRVM,91 Hove St,NaN,M3H,Single/Semi-detached House,6,York Centre
1,6901345,STR-2301-GXRRVV,91 Shaw St,NaN,M6J,Townhouse/ Row House,10,Spadina-Fort York
2,6901346,STR-2107-HQZHHK,64 Millicent St,2,M6H,Duplex/Triplex/Fourplex,9,Davenport
3,6901347,STR-2307-FPTHHQ,2 Hurdman St,NaN,M6M,Single/Semi-detached House,5,York South-Weston
4,6901348,STR-2310-FYBRVR,47 Vradenberg Dr,NaN,M1T,Single/Semi-detached House,22,Scarborough-Agincourt
5,6901349,STR-2601-GPVYBT,58 Beverley St,1,M5T,Duplex/Triplex/Fourplex,10,Spadina-Fort York
6,6901350,STR-2602-HXDFBY,7A Claremont St,NaN,M6J,Townhouse/ Row House,10,Spadina-Fort York
7,6901351,STR-2603-FFBYBP,97 Rogers Rd,NaN,M6E,Single/Semi-detached House,9,Davenport
8,6901352,STR-2009-GGPDPF,36 Maitland St,H04,M4Y,Apartment,13,Toronto Centre
9,6901353,STR-2009-HBWKPJ,1339 Lansdowne Ave,2,M6H,Single/Semi-detached House,9,Davenport

In [11]:
st_rental_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   _id                           10 non-null     int64
 1   operator_registration_number  10 non-null     str
 2   address                       10 non-null     str
 3   unit                          4 non-null      str
 4   postal_code                   10 non-null     str
 5   property_type                 10 non-null     str
 6   ward_number                   10 non-null     int64
 7   ward_name                     10 non-null     str
dtypes: int64(2), str(6)
memory usage: 772.0 bytes

### Registration and Rental Renewals

In [12]:
# The URL for an actual Excel file
url = 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/602f7450-23be-467b-8832-a768918c8dc0/resource/918ffe2b-a263-4286-93a5-8c9be1d814a4/download/Short%20Term%20Rental%20Program%20Data.csv'

# 1. Read just the first 10 rows to 'peek'
# Use pd.read_excel for .xlsx files
df_peek = pd.read_csv(url, nrows=10)

# 2. Look at the column names
print(f"Total Columns: {len(df_peek.columns)}")
print(df_peek.columns)

df_peek.head(10)

Total Columns: 6
Index(['_id', 'Data Name', 'Data Type', 'Year', 'Month Name', 'Data Count'], dtype='str')

,_id,Data Name,Data Type,Year,Month Name,Data Count
0,1,Registration applications received,Registration and Registration Renewal,2021,March,187
1,2,Registration applications received,Registration and Registration Renewal,2021,June,171
2,3,Registration applications received,Registration and Registration Renewal,2022,January,239
3,4,Registration applications received,Registration and Registration Renewal,2022,February,243
4,5,Registration applications received,Registration and Registration Renewal,2022,May,478
5,6,Registration applications received,Registration and Registration Renewal,2022,July,555
6,7,Registration applications received,Registration and Registration Renewal,2022,September,476
7,8,Registration applications received,Registration and Registration Renewal,2023,August,603
8,9,Registration applications received,Registration and Registration Renewal,2023,October,563
9,10,Registration applications received,Registration and Registration Renewal,2023,November,507